/*
* @author Eric Choo
* @license : MIT
*/

// white - gray - black
export const white = '#FFFFFF'
export const ghostwhite = '#F8F8FF'
export const whitesmoke = '#F5F5F5'
export const gainsboro = '#DCDCDC'
export const lightgray = '#D3D3D3'
export const silver = '#C0C0C0'
export const darkgray = '#A9A9A9'
export const lightslategray = '#778899'
export const slategray = '#708090'
export const gray = '#808080'
export const dimgray = '#696969'
export const black = '#000000'

// blues
export const cyan = '#00FFFF'
export const aliceblue = '#F0F8FF'
export const azure = '#F0FFFF'
export const lightcyan = '#E0FFFF'
export const paleturquoise = '#AFEEEE'
export const powderblue = '#B0E0E6'
export const skyblue = '#87CECB'
export const turquoise = '#40E0D0'
export const mediumturquoise = '#48D1CC'
export const darkturquoise = '#00CED1'
export const darkcyan = '#008B8B'
export const steelblue = '#4682B4'
export const lightblue = '#ADD8E6'
export const lightsteelblue = '#B0C4DE'
export const lightskyblue = '#87CEFA'
export const deepskyblue = '#00BFFF'
export const cornflowerblue = '#6495ED'
export const dodgerblue = '#1E90FF'
export const royalblue = '#4169E1'
export const mediumblue = '#0000CD'
export const darkslateblue = '#483D8B'
export const darkblue = '#00008B'
export const navy = '#000080'
export const midnightblue = '#191970'

// greens
export const honeydew = '#F0FFF0'
export const aquamarine = '#7FFFD4'
export const palegreen = '#98F898'
export const lightgreen = '#90EE90'
export const springgreen = '#00FF7F'
export const mediumspringgreen = '#00FA9A'
export const greenyellow = '#ADFF2F'
export const lawngreen = '#7CFC00'
export const chartreuse = '#7FFF00'
export const lime = '#00FF00'
export const limegreen = '#32CD32'
export const yellowgreen = '#9ACD32'
export const darkseagreen = '#8FBC8F'
export const mediumseagreen = '#3CB371'
export const lightseagreen = '#20B2AA'
export const green = '#008080'
export const seagreen = '#2E8B57'
export const forestgreen = '#228B22'
export const darkgreen = '#006400'
export const olive = '#808000'
export const darkolivegreen = '#556B2F'
export const darkslategray = '#2F4F4F'

// gold - yellow
export const lightyellow = '#FFFFE0'
export const lightgoldenrodyellow = '#FAFAD2'
export const lemonchiffon = '#FFFACD'
export const beige = '#F5F5DC'
export const palegoldenrod = '#EEE8AA'
export const khaki = '#F0E68C'
export const darkkhaki = '#BDB76B'
export const yellow = '#FFFF00'
export const gold = '#FFD700'
export const goldenrod = '#DAA520'
export const darkgoldenrod = '#B8860B'

//tan - orange - cream
export const mintcream = '#F5FFFA'
export const ivory = '#FFFFF0'
export const floralwhite = '#FFFAF0'
export const snow = '#FFFAFA'
export const seashell = '#FFF5EE'
export const linen = '#FAF0E6'
export const oldlace = '#FDF5E6'
export const cornsilk = '#FFF8DC'
export const papayawhip = '#FFEFD5'
export const antuquewhite = '#FAEBD7'
export const bisque = '#FFE4C4'
export const peachpuff = '#FFDAB9'
export const navajowhite = '#FFDEAD'
export const moccasin = '#FFE4B5'
export const wheat = '#F5DEB3'
export const burlywood = '#DEB887'
export const tan = '#D2B48C'
export const peru = '#CD853F'
export const sandybrown = '#F4A460'
export const darkorange = '#FF8C00'
export const coral = '#FF7F50'
export const tomato = '#FF6347'
export const orangered = '#FF4500'
export const lightsalmon = '#FFA07A'
export const salmon = '#FA8072'
export const lightcorol = '#F08080'
export const rosybrown = '#BC8F8F'
export const indianred = '#CD5C5C'
export const chocolate = '#D2691E'
export const sienna = '#A0522D'
export const saddlebrown = '#8B4513'

// purple
export const lavender = '#E6E6FA'
export const thistle = '#D8BFD8'
export const plum = '#DDA0DD'
export const violet = '#EE82EE'
export const mediumorchid = '#BA55D3'
export const mediumslateblue = '#7B68EE'
export const mediumpurple = '#9370DB'
export const slateblue = '#6A5ACD'
export const darkviolet = '#9400D3'
export const blueviolet = '#8A2BE2'
export const darkorchid = '#9932CC'
export const darkmagenta = '#8B008B'
export const purple = '#800080'
export const indigo = '#4B0082'

// pink
export const lavenderblush = '#FFF0F5'
export const mistyrose = '#FFE4E1'
export const lightpink = '#FFB6C1'
export const pink = '#FFC0CB'
export const hotpink = '#FF69B4'
export const magenta = '#FF00FF'
export const deeppink = '#FF1493'
export const palevioletred = '#D87093'
export const mediumvioletred = '#C71585'

// red
export const red = '#FF0000'
export const crimson = '#DC143C'
export const firebrick = '#B22222'
export const brown = '#A52A2A'
export const darkred = '#8B0000'
export const maroon = '#800000'
